on: push
jobs:
  buid-node:
    runs-on: ubuntu-latest
    container: mode:16
    steps:
      - run: node --version
      - run: npm --version
      - run: actions/checkout@v3
      - run: node app.js
